// Translations
const translations = {
    en: {
        aiGreeting: "Hi, I'm Herakles — Your AI Assistant. What do you want to learn?",
        summarize: "Summarize",
        bullets: "Bullets",
        explain: "Explain",
        explainConcepts: "Explain Concepts",
        stepByStep: "Step by Step",
        glossary: "Glossary",
        analyze: "Analyze",
        evaluate: "Evaluate",
        improvements: "Improvements",
        extractDetails: "Extract Details",
        actions: "Actions",
        nextActions: "Next Actions",
        actionPlan: "Action Plan",
        webSearch: "Web Search",
        resources: "Resources",
        quiz: "Quiz",
        newChat: "New Chat",
        messagePlaceholder: "Type a message...",
        navMenu: "Menu",
        navApps: "Apps",
        navLearn: "Learn",
        errorMessage: "An error occurred. Please try again.",
        browserNotSupported: "Your browser does not support audio recording",
        microphoneError: "Error accessing microphone. Please check your settings and try again.",
        offlineMessage: "You are currently offline. Some features may not be available.",
        chatHistory: "Chat History",
        languageName: "In English",
        send: "Send",
        attachment: "Attach file",
        darkMode: "Toggle dark mode",
        sidebar: "Chat history",
        closeSidebar: "Close sidebar",
        translate: "Translate",
        more: "More"
    },
    es: {
        aiGreeting: "Hola, soy Herakles — Tu Asistente de IA. ¿Qué quieres aprender?",
        summarize: "Resumir",
        bullets: "Viñetas",
        explain: "Explicar",
        explainConcepts: "Explicar Conceptos",
        stepByStep: "Paso a Paso",
        glossary: "Glosario",
        analyze: "Analizar",
        evaluate: "Evaluar",
        improvements: "Mejoras",
        extractDetails: "Extraer Detalles",
        actions: "Acciones",
        nextActions: "Próximas Acciones",
        actionPlan: "Plan de Acción",
        webSearch: "Búsqueda Web",
        resources: "Recursos",
        quiz: "Cuestionario",
        newChat: "Nueva Conversación",
        messagePlaceholder: "Escribe un mensaje...",
        navMenu: "Menú",
        navApps: "Aplicaciones",
        navLearn: "Aprender",
        errorMessage: "Ocurrió un error. Por favor, inténtalo de nuevo.",
        browserNotSupported: "Tu navegador no soporta la grabación de audio",
        microphoneError: "Error al acceder al micrófono. Por favor, verifica tu configuración e intenta de nuevo.",
        offlineMessage: "Actualmente estás desconectado. Algunas funciones pueden no estar disponibles.",
        chatHistory: "Historial de Chat",
        languageName: "En Español",
        send: "Enviar",
        attachment: "Adjuntar archivo",
        darkMode: "Cambiar modo oscuro",
        sidebar: "Historial de chat",
        closeSidebar: "Cerrar barra lateral",
        translate: "Traducir",
        more: "Más"
    },
    fr: {
        aiGreeting: "Bonjour, je suis Herakles — Votre Assistant IA. Que voulez-vous apprendre ?",
        summarize: "Résumer",
        bullets: "Puces",
        explain: "Expliquer",
        explainConcepts: "Expliquer les Concepts",
        stepByStep: "Étape par Étape",
        glossary: "Glossaire",
        analyze: "Analyser",
        evaluate: "Évaluer",
        improvements: "Améliorations",
        extractDetails: "Extraire les Détails",
        actions: "Actions",
        nextActions: "Prochaines Actions",
        actionPlan: "Plan d'Action",
        webSearch: "Recherche Web",
        resources: "Ressources",
        quiz: "Quiz",
        newChat: "Nouvelle Conversation",
        messagePlaceholder: "Tapez un message..
