Skip to content
Navigation Menu
jaredgrogan
/
landing

Type / to search
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Files
Go to file
api
calendar.js
chat.js
old
vue-experiment
.env
.gitignore
2do2day.html
7daycamp.html
MLcycler.html
MLvocab
about2.html
about4.html
about5.html
admin2.html
adminback.html
adminsys.html
adminsys1.html
advance-script.js
advance.css
advance.html
agency.css
agency.html
agency2.css
agency2.js
agency3.css
agency3.js
agency4.css
agency5.css
agentadmin.html
ai-chat.html
ai-chat2.html
ai-chat5.html
ai-test-chat.html
aiagency.html
aiassistant.html
aico-script.js
aico.html
aico.svg
aicoagency.html
aicoagency2.html
aicoagency3.html
aicord.css
aicord.html
aicord.js
aicosystem.html
aidevtools.html
ailanding.html
aimedia.html
aios.html
animation.html
animation.js
apiconfiguration.html
apigui.html
apipayment.html
app-footer.html
app-new.html
app-new10.html
app-new12.html
app-new13.html
app-new3.html
app-new4.html
app-new5.html
app-new6.html
app-new7.html
app-new8.html
app-news2.html
app-test.html
app.css
app.html
app.js
app.py
app.vue
app10.html
app101.html
app102.html
app103.html
app105.html
app11.html
app12.html
app13.html
app15-gold.html
app4.html
app5.html
app7.html
app8.html
app9.html
app99.html
apps-test.html
apps101.html
apps102.html
apps103.html
apps105.html
apps106.html
apps99.html
arabicchat.html
arabicoffice.html
archive-og-stable-app-09-2024.html
assistant.html
awesome.html
backendadmin.html
berkeley
berkeley.html
berkeley.js
berkeley2.css
berkeley2.html
berkeley2.js
betatest.css
betatest.html
betatest.js
betatest2.css
betatest2.html
betatest2.js
betatest3.css
betatest3.html
betatest3.js
betatest4.html
betatest4.js
bloom.html
blueocean.html
bootcamp.css
bootcamp.html
bootcamp.js
bootcamp100.html
bootcamp101.html
bootcamp99.html
broadcast.html
broadcast2.html
cal2.js
cal3.css
calendar-script.js
calendar-script2.js
calendar-style.css
calendar-style2.css
calendar-style3.css
calendar.css
calendar.html
calendar2.html
campaign.html
careers.html
careers2.html
celebrate-script.js
celebrate.css
celebrate.html
chat-assistant.html
chat-console16.html
chat-console18.html
chat-console19.html
chat-console20.html
chat-console21.html
chat-console22.html
chat-console23.html
chat-console24.html
chat-console25.html
chat-console26.html
chat-console27.html
chat-console28.html
chat-console30.html
chat-console31.html
chat-console32.html
chat-console33.html
chat-console35.html
chat-console36.html
chat-console39.html
chat-console40.html
chat-console41.html
chat-console42.html
chat-console44.html
chat-console45.html
chat-console46.html
chat-console47.html
chat-console48.html
chat-console49.html
chat-console50.html
chat-console52.html
chat-console53.html
chat-console54.html
chat-different-bg-color.html
chat-min.html
chat-retire-errors.html
chat-script2.js
chat-style.css
chat-style2.css
chat-style3.html
chat-style4.css
chat-style7.css
chat.html
chat100.html
chat101.html
chat111.html
chat112.html
chat113.html
chat114.html
chat115.html
chat116.html
chat117.html
chat118.html
chat2.html
chat3.html
chat33.html
chat5.html
chat77.html
chat88.html
chatconsole.html
chatconsole11.html
chatconsole18.html
chatconsole2.html
chatconsole3.html
chatconsole4.html
chatconsole5.html
chatconsole6.html
chatconsole7.html
chatconsole8.html
chatconsole9.html
chatextract.html
chatllmintegration.html
chatog.html
chatspace.html
chatspace2.html
chatting.css
chatting.html
cloud.html
cloud1.svg
cloud2.html
cloud7.html
cloud9.html
cognitivenano.html
color.html
comms.html
comms1.html
community.html
complete.html
component-script.js
component.css
component.html
concept.css
concept.html
concept.js
consoledev.html
consoledev2.html
consoledev3.html
contact.html
conversations.html
conversations2.html
conversations4.html
copy.html
cosmic.html
cosmic.jpg
crm.html
crm2.html
crm3.html
crm4.html
dash.html
datavisuals.html
deeplearning.html
devtool.html
diary.html
diary2.html
diary3.html
discover.css
discover.html
docker.html
docker1.html
docker2.html
docker3.html
docker4.html
docker5.html
dockertutorial.html
docs.html
docuchat.html
docuchat1.html
docuchat2.html
docuchat3.html
docuchat4.html
docuchat5.html
docuchat6.html
docuchat7.html
documentchat.html
documentchat2.html
ebertbeta.html
education.html
elevate-script.js
elevate.css
elevate.html
english.html
experiment.html
experiment.js
explorer.css
explorer.html
explorer.js
explorer99.html
favicon.svg
favicon10.svg
favicon2.svg
favicon3.svg
favicon4.svg
favicon5.svg
favicon6.svg
favicon7.svg
favicon8.svg
favicon9.svg
favicon_small.svg
favicon_white.svg
features.html
fireworks.html
five.css
five.html
five.js
flashcard.html
fold.html
footer.css
footer.html
four.css
four.html
four.js
galaxy.html
game.js
games.html
geo.html
get-pro.html
getpro.html
globalchat.html
globalchat101.html
globalchat2.html
globalchat3.html
globalchat4.html
globalchat5.html
globalchat55.html
globalchat77.html
globalchat88.html
globalchat99.html
globalconsole-script.js
globalconsole.css
globalconsole.html
globalnow-script.js
globalnow.css
globalnow.html
graph.css
graphnet.css
graphnet.html
graphnet.js
handbook1.html
herakles.html
herakles99.html
home.vue
home100.html
home101.html
home105html
home99.html
homepage101.html
homepage102.html
homepage104.html
homepage105.html
homepage106.html
homepage107.html
homepage99.html
hub.html
hub2.html
ig.html
ig2.html
ig3.html
index.html
index2.html
index3.html
index8.html
innovate.css
innovate.html
innovate.js
innovate2.css
innovate2.html
innovate2.js
innovate3.css
innovate3.html
innovate3.js
innovation.css
innovation.html
innovation.js
innovation2.css
innovation2.html
innovation3.css
innovation3.html
innovation8.css
innovation8.html
innovation8.js
join-pro.html
knowledge.html
labs.html
labs2.html
labs3.html
labs4.html
labs5.html
landing102.html
landing99.html
language.html
languages.css
languages.html
languages.js
learn99.html
learning.html
learningdash.html
learningoutcomes.html
learningprogress.html
linearalgebra.html
linga3.html
lingua.css
lingua.html
lingua.js
lingua2.css
lingua2.html
lingua2.js
lingua3.css
lingua3.html
lingua3.js
lingua4.css
lingua4.html
lingua4.js
linguafranca.css
linguafranca.html
linguafranca.js
linguafranca2.js
login.html
login2.html
login3.html
maintest.html
markethub.html
mars.html
mars2.html
marsthegame.html
math.html
math2.html
math3.html
math4.html
matrix.html
maxlanguages-chat-notworking.html
mediacenter.html
mediaconsole.html
mediaconsole2.html
mediaconsole5.html
mediaconsole6.html
mediaplay.html
mediaplayer.html
mediaplayer2.html
mediaplayer3.html
mediaplayer4.html
mediaplayer5.html
mediaplayer6.html
mediatest.html
mediaviewer.css
mediaviewer.html
mediaviewer.js
mic-black.svg
mic-white.svg
minichat.html
minimalist-chat.html
minimalist.html
mockup.html
mockup10.html
mockup11.html
mockup2.html
mockup3.html
mockup4.html
mockup5.html
mockup6.html
mockup7.html
mockup8.html
mockup9.html
module.html
moon-icon.svg
multilanguage.html
mvp-script.js
mvp.css
mvp.html
mvp2.html
mvp3-script.js
mvp3.css
mvp3.html
mvp4-script.js
mvp4.css
mvp4.html
mvp5-script.js
mvp5.css
mvp5.html
mydash.html
mydash2.html
mydash3.html
mydash4.html
mydash5.html
mydash6.html
mydash7.html
mylist.html
myprojects.html
namedentity.html
natlang.html
naturallanguage.html
navtest.html
neo.html
network.html
neural-script.js
neural.css
neuralanimation.html
neuralnetwork.css
neuralnetwork.html
neuralnetwork.js
neuralnetworks.html
neuron.css
neuron.html
neuron.js
neuron2-script.js
neuron2.html
neuron3.html
neuron5.css
neuron5.html
neuron6.html
new.css
new.html
new.js
new2.css
new2.js
newchat.html
newconsole-note.html
newconsole-script.js
newconsole.css
newconsole.html
newhome.html
newhome2.html
newhome3.html
newhome4.html
newhome5.html
newhome6.html
newhome7.html
newhome8.html
newmedia.html
newmediaplayer.html
newminichat.html
newsample.html
newsample2.html
newstyle.css
newtemplate.html
newtemplate2.html
newtemplate3.html
newtemplate4.html
nichedown.html
nightchat.css
nightchat.html
nightchat.js
nlcode.html
nli.html
nltk.html
nltk2.html
nocode.html
node-script.js
node.css
node.html
node2.html
node3.html
node4.css
node4.html
note.css
note.html
note.js
note2.css
note3.css
notebook.css
notebook.html
notebook.js
notes.html
novasessions.html
office.css
office.html
office.js
og-stable-todotoday.html
onboarding.html
original-index.html
outcomes.html
overflow1.html
overflow2.html
overflow3.html
package.json
pad.html
pad.js
page2.html
particles.html
particles2.html
persona.html
personallogo.html
perspective.css
perspective.html
perspective.js
pilotinstructions.html
plan.css
plan.html
plan.js
planner.html
preview.css
pricing.css
pricing.html
pricing.js
pricing2.html
pricing4.html
pricing5.html
pricing6.html
prism.js
product.html
product101.html
product2.html
productionready.html
productions.html
productivity.html
productivity2.html
producttour.html
profile-script.js
profile-style.css
profilepage.html
program.html
projectspace.css
projectspace.html
projectspace.js
prompts1.html
pythonconcept.html
pythonconcepts.html
pythonconcepts2.html
pythonconcepts4.html
pytorch.html
pytorch2.html
pytorch3.html
pytorchintro.html
rag-script.js
rag-style.css
rag.html
ragengine.html
ragengine2.html
ragsearch.html
rasa2.html
rasachatbot.html
rasachatbots.html
redesign.css
redesign.html
redesign2.css
redesign2.html
reflector.html
reflectorstudios.html
retire-ai-old2-chat.html
retire-og-server.js
retire-old-chat.html
retire-pre-ai-chat.html
retired-chat.html
retro-note.html
sales.html
sales1.html
sales2.html
sales3.html
sales5.html
salespage.html
sample.css
sample.html
sample.js
scikit.html
script.js
script10.js
script2.js
script3.js
script4.js
script5.js
script6.js
script8.js
script9.js
scriptnight.js
scriptstory.js
scriptstory2.js
scriptstory3.js
scriptstory4.js
select.html
selection.html
selector.html
server-improved-retired-lastbefore-api.js
server-old2.js
server-old3.js
server.js
server_new.js
singapore.html
spacegame.html
stable-retire-chat.html
standards.html
story.html
studio.css
studio.html
studio.js
studio2.css
studio2.html
studio2.js
studio3.css
studio3.html
studio3.js
studio4.css
studio4.html
studio4.js
studio7.css
style-3.css
style-uni.css
styles.css
styles4.css
styles5.css
styles8.css
styles9.css
submit-email.html
sun-icon.svg
sunset1.html
sunset2.html
sunset3.html
support.html
swissarmy.html
taskchat.html
taskchat1.html
taskchat10.html
taskchat11.html
taskchat12.html
taskchat13.html
taskchat14.html
taskchat15.html
taskchat17.html
taskchat18.html
taskchat2.html
taskchat20.html
taskchat21.html
taskchat22.html
taskchat23.html
taskchat24.html
taskchat25.html
taskchat26.html
taskchat27.html
taskchat28.html
taskchat29.html
taskchat3.html
taskchat4.html
taskchat5.html
taskchat6.html
taskchat7.html
taskchat8.html
taskchat9.html
taskcombo.html
taskcombo2.html
taskcombo3.html
taskcombo4.html
taskcombo5.html
taskcombo6.html
taskcombo7.html
template.html
tensor3.html
tensor4.html
tensor5.html
tensor6.html
tensor7.html
tensorflow.html
test2.html
test3.html
todo.html
todotoday.html
transfer.html
trial1.html
trial2.html
trial3.html
trial4.html
trial5.html
trynow.html
turing.html
turing.js
tutorial-chat.html
tutorial-tensorflow2.html
tutorial7.html
tutorials-math2.html
tutorials-python.html
tutorials.html
tutorials10.html
tutorials2.html
tutorials3.html
tutorials5.html
tutorials6.html
tutorials8.html
tutorials9.html
tutorialstest.html
tutortest.css
tutortest.html
u_micro.svg
unitychat.html
unitychat2.html
universitasstudio.html
universitasstudio2.html
universitasstudio3.html
user_registration_backend.py
venture.html
videos1.css
videos1.html
videos1.js
visual-script.js
visual-script2.js
visual-script3.js
visual-script4.js
visual.css
visual.html
visual2.css
visual2.html
visualize.css
visualize.html
visualize.js
visualize2.css
viva-check.html
viva-drag.html
viva.html
viva1.html
viva10.html
viva11.html
viva12.html
viva13.html
viva14.html
viva15.html
viva16.html
viva17.html
viva18.html
viva19.html
viva2.html
viva20.html
viva21.html
viva22.html
viva23.html
viva24.html
viva25.html
viva26.html
viva27.html
viva28.html
viva29.html
viva3.html
viva30.html
viva31.html
viva32.html
viva33.html
viva34.html
viva36.html
viva37.html
viva38.html
viva39.html
viva4.html
viva40.html
viva41.html
viva42.html
viva5.html
viva7.html
viva8.html
viva9.html
vivamono.html
voice-script.js
voice-style.css
voice.html
voice2.html
voicechat.css
voicechat.html
voiceui.html
welcome.html
word2vec.html
wordembeddings.html
wordspace-script.js
wordspace.html
work.html
work10.html
work11.html
work12.html
work14.html
work16.html
work17.html
work2.html
work3.html
work30.html
work31.html
work33.html
work34.html
work4.html
work5.html
work50.html
work51.html
work52.html
work53.html
work54.html
work55.html
work7.html
work8.html
work9.html
workspace.css
workspace.html
workspace.js
worldchat-script.js
worldchat.css
worldchat.html
worldchat2.css
worldchat99.html
worldconsole-script.js
worldconsole.css
worldconsole.html
xpro1.html
xpro2.html
Creating a new file in landing
Breadcrumbslanding/api
/
chat.js
in
main

Edit

Preview
Indent mode

Spaces
Indent size

2
Line wrap mode

No wrap
Editing chat.js file contents
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
      {
        headers: {
          Authorization: `Bearer ${process.env.PERPLEXITY_API_KEY}`,
          'Content-Type': 'application/json'
        }
      }
    );
    return response.data.choices[0].message.content;
  } catch (error) {
    console.error('Perplexity API Error:', error);
    throw error;
  }
}

// Chat endpoint
app.post('/api/chat', async (req, res) => {
  try {
    const { message, usePerplexity } = req.body;
    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    let response;
    console.log('Decrypting OpenAI API Key using API Gateway...');
    const decryptResponse = await axios.post(
      process.env.API_GATEWAY_URL,
      {},
      { headers: { 'Content-Type': 'application/json' } }
    );
    const decryptedApiKey = decryptResponse.data;

    if (!decryptedApiKey) {
      throw new Error('Decryption failed or key not found in the response.');
    }

    if (usePerplexity) {
      console.log('Calling Perplexity API as Herakles AI...');
      response = await callPerplexityAPI(message);
    } else {
      console.log('Calling OpenAI API as Herakles AI...');
      response = await callOpenAIAPI(message, decryptedApiKey);
    }

    res.json({ response });
  } catch (error) {
    console.error('Error in /api/chat:', error.message);
    res.status(500).json({
      error: 'An error occurred while processing your request',
      details: error.message,
      stack: error.stack
    });
  }
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

// Server setup
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));

module.exports = app; // For testing purposes
Use Control + Shift + m to toggle the tab key moving focus. Alternatively, use esc then tab to move to the next interactive element on the page.
New File at api · jaredgrogan/landing 
